#!/bin/sh
#
# wget for mortals
#
# Avoid unnecessary index sort files...
# https://askubuntu.com/questions/719410/wget-web-crawler-retrieves-unwanted-index-html-index-files
#

wget \
     --adjust-extension \
     --backup-converted \
     --convert-links \
     --level=inf \
     --no-parent \
     --page-requisites \
     --random-wait \
     --recursive \
     --timestamping \
     --tries=inf \
     -R '\?C=' \
     "$@"
