#!/bin/sh

id=$(xinput list | grep -i "TouchPad" | egrep -o "id=.." | tr -d "id=")
#id=$(xinput list | grep "Generic Mouse" | egrep -o "id=.." | tr -d "id=")

xinput set-prop ${id} "Device Enabled" 0
