#!/usr/bin/python

import sys

stopWordFile = sys.argv[1]
with open(stopWordFile, "rb") as f:
    stop_words = [line.strip() for line in f.readlines()]

for input_line in sys.stdin.readlines():
    locate = [(input_line.find(stop_word) == -1) for stop_word in stop_words]
    if False not in locate:
        sys.stdout.write(input_line)

sys.stdout.flush()
