#!/usr/bin/python
import os
import fnmatch


def gen_find(filepat, topdir):
    for path, dirlist, filelist in os.walk(topdir):
        for name in fnmatch.filter(filelist, filepat):
            yield os.path.join(path, name)


def gen_open(filenames):
    for filename in filenames:
        yield (filename, open(filename))


def gen_cat(files):
    for filename, afile in files:
        for line in afile:
            yield (filename, line)


def gen_grep(data_pattern, lines):
    for filename, line in lines:
        if data_pattern.search(line):
            yield (filename, line)


if __name__ == '__main__':
    import sys
    import re

    topdir = sys.argv[1]
    file_pattern = sys.argv[2]
    data_pattern = re.compile(sys.argv[3])
    for filename, line in gen_grep(
            data_pattern, gen_cat(gen_open(
                gen_find(file_pattern, topdir)))):
        print '{0}: {1}'.format(filename, line.strip())
