#!/usr/bin/python
import os
import sys
import fnmatch


def gen_find(filepat, topdir):
    for path, dirlist, filelist in os.walk(topdir):
        for name in fnmatch.filter(filelist, filepat):
            yield os.path.join(path, name)


if __name__ == '__main__':
    topdir = sys.argv[1]
    pattern = sys.argv[2]
    for filename in gen_find(pattern, topdir):
        print filename
